# Generated by Django 5.0.2 on 2024-04-05 18:16

import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedModel',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('parameters', models.JSONField(help_text='set of variable parameters and their values', unique=True)),
                ('output_parameters', models.JSONField(blank=True, help_text='set of output parameters and their values', null=True)),
            ],
            options={
                'db_table': 'generated_model',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('creation_date', models.DateTimeField(auto_now=True, help_text='Date of Creation')),
                ('project_name', models.CharField(db_column='project_name', help_text='Project Name', max_length=256, primary_key=True, serialize=False)),
                ('variable_metadata', models.JSONField(help_text='Set of variable parameters and their units')),
                ('output_metadata', models.JSONField(help_text='Set of output parameters and their units')),
                ('assets', models.JSONField(help_text='Set of asset names')),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='AssetFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(editable=False, help_text='File associated with a generated model', upload_to='./assets')),
                ('tag', models.CharField(editable=False, help_text='File tag of the asset', max_length=30)),
                ('generated_model', models.ForeignKey(help_text='Foreign Key to Associated Generated Model', on_delete=django.db.models.deletion.PROTECT, related_name='files', to='main_process.generatedmodel')),
            ],
        ),
        migrations.AddField(
            model_name='generatedmodel',
            name='project',
            field=models.ForeignKey(help_text='Foreign Key to Associated Project', on_delete=django.db.models.deletion.PROTECT, to='main_process.project'),
        ),
        migrations.AddIndex(
            model_name='generatedmodel',
            index=django.contrib.postgres.indexes.GinIndex(fields=['parameters'], name='generated_m_paramet_cc61f0_gin'),
        ),
    ]
