# Generated by Django 5.0.2 on 2024-03-10 17:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_process', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedmodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
