# Generated by Django 5.0.2 on 2024-05-30 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_process', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedmodel',
            name='scoped_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(help_text='Project Name', max_length=256, primary_key=True, serialize=False),
        ),
    ]
