# Generated by Django 5.0.2 on 2024-07-24 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_process', '0002_generatedmodel_scoped_id_alter_project_project_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMetadata',
            fields=[
                ('project', models.ForeignKey(help_text='Foreign Key to Associated Project', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main_process.project')),
                ('captions', models.JSONField(help_text='Set of captions to be displayed for the project')),
                ('description', models.TextField(help_text='Markdown description of the project')),
            ],
        ),
    ]
