# Generated by Django 5.0.2 on 2024-03-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_process', '0003_project_assets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='assets',
            field=models.JSONField(default=dict, help_text='Set of asset names'),
        ),
    ]
