# Generated by Django 5.0.2 on 2024-08-24 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_process', '0003_projectmetadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkdownDocument',
            fields=[
                ('slug', models.TextField(help_text='Identifies the document', primary_key=True, serialize=False, unique=True)),
                ('text', models.TextField(blank=True, help_text='Markdown text')),
            ],
        ),
        migrations.AddField(
            model_name='projectmetadata',
            name='human_name',
            field=models.TextField(default='', help_text='Human readable name of the project.'),
        ),
        migrations.AlterField(
            model_name='projectmetadata',
            name='captions',
            field=models.JSONField(default='{}', help_text='Set of captions to be displayed for the project'),
        ),
        migrations.AlterField(
            model_name='projectmetadata',
            name='description',
            field=models.ForeignKey(help_text='Markdown description of the project', on_delete=django.db.models.deletion.DO_NOTHING, to='main_process.markdowndocument'),
        ),
    ]
