# Generated by Django 5.0.2 on 2024-03-13 20:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_process', '0004_alter_project_assets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedmodel',
            name='assets',
        ),
        migrations.AlterModelTable(
            name='generatedmodel',
            table='generated_model',
        ),
        migrations.CreateModel(
            name='AssetFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(editable=False, help_text='File associated with a generated model', upload_to='')),
                ('tag', models.CharField(editable=False, help_text='File tag of the asset', max_length=30)),
                ('generated_model', models.ForeignKey(help_text='Foreign Key to Associated Generated Model', on_delete=django.db.models.deletion.PROTECT, to='main_process.generatedmodel')),
            ],
        ),
    ]
