# Generated by Django 5.0.2 on 2024-03-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_process', '0005_remove_generatedmodel_assets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedmodel',
            name='assets',
            field=models.JSONField(default=[], help_text='Set of Asset Types and their URLs'),
        ),
    ]
