# Generated by Django 5.0.2 on 2024-03-13 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_process', '0006_generatedmodel_assets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedmodel',
            name='assets',
        ),
        migrations.AlterField(
            model_name='generatedmodel',
            name='project_key',
            field=models.ForeignKey(help_text='Foreign Key to Associated Project', on_delete=django.db.models.deletion.PROTECT, to='main_process.project'),
        ),
    ]
