# Generated by Django 5.0.2 on 2024-03-13 22:20

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_process', '0007_remove_generatedmodel_assets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetfile',
            name='file',
            field=models.FileField(editable=False, help_text='File associated with a generated model', upload_to='./assets'),
        ),
        migrations.AddIndex(
            model_name='generatedmodel',
            index=django.contrib.postgres.indexes.GinIndex(fields=['parameters'], name='generated_m_paramet_cc61f0_gin'),
        ),
    ]
