# Generated by Django 5.0.2 on 2024-03-13 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_process', '0008_alter_assetfile_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedmodel',
            name='parameters',
            field=models.JSONField(help_text='Set of Parameters and their Values', unique=True),
        ),
    ]
