# Generated by Django 5.0.2 on 2024-03-21 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_process', '0009_alter_generatedmodel_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetfile',
            name='generated_model',
            field=models.ForeignKey(help_text='Foreign Key to Associated Generated Model', on_delete=django.db.models.deletion.PROTECT, related_name='files', to='main_process.generatedmodel'),
        ),
    ]
