# Generated by Django 5.0.2 on 2024-04-03 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_process', '0011_alter_project_assets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generatedmodel',
            old_name='project_key',
            new_name='project',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_id',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(db_column='project_name', editable=False,
                                   help_text='Project Name', max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='generatedmodel',
            name='id',
            field=models.BigAutoField(
                editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='generatedmodel',
            name='project',
            field=models.ForeignKey(help_text='Foreign Key to Associated Project',
                                    on_delete=django.db.models.deletion.PROTECT, to='main_process.project'),
        ),
    ]
