# Generated by Django 5.0.2 on 2024-04-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_process', '0012_rename_project_key_generatedmodel_project_and_more_squashed_0013_alter_generatedmodel_id_alter_generatedmodel_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedmodel',
            name='parameters',
            field=models.JSONField(help_text='set of variable parameters and their values', unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='output_metadata',
            field=models.JSONField(help_text='Set of output parameters and their units'),
        ),
    ]
