# Generated by Django 5.0.2 on 2024-04-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_process', '0014_alter_generatedmodel_parameters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedmodel',
            name='output_parameters',
            field=models.JSONField(blank=True, help_text='set of output parameters and their values', null=True),
        ),
    ]
