# Generated by Django 5.0.2 on 2024-04-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_process', '0015_generatedmodel_output_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(db_column='project_name', help_text='Project Name', max_length=256, primary_key=True, serialize=False),
        ),
    ]
